# Generated by Django 3.0 on 2019-12-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField(max_length=150)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='profile')),
                ('activo', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False)),
            ],
        ),
    ]
