# Generated by Django 3.0 on 2019-12-06 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_launcher', '0002_auto_20191204_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('skip', models.BooleanField(default=False)),
                ('start', models.DateTimeField(auto_now=True)),
                ('end', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=4)),
                ('package', models.CharField(max_length=45)),
                ('uri', models.CharField(max_length=100)),
                ('banner', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=45)),
                ('es', models.CharField(max_length=45)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_launcher.App')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=45)),
                ('es', models.CharField(max_length=45)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_launcher.App')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='media/backgrounds')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_launcher.App')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.TextField(max_length=150)),
                ('es', models.TextField(max_length=150)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_launcher.App')),
            ],
        ),
    ]
