# Generated by Django 3.0 on 2019-12-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_launcher', '0003_app_description_image_title_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='app',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
