# Generated by Django 3.0 on 2019-12-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_launcher', '0004_auto_20191206_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='app',
        ),
        migrations.RemoveField(
            model_name='image',
            name='app',
        ),
        migrations.RemoveField(
            model_name='title',
            name='app',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='app',
        ),
    ]
