# Generated by Django 3.0 on 2019-12-09 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_launcher', '0005_auto_20191209_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin_launcher.Description'),
        ),
        migrations.AddField(
            model_name='app',
            name='title',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin_launcher.Title'),
        ),
        migrations.AddField(
            model_name='app',
            name='trailer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin_launcher.Trailer'),
        ),
    ]
