# Generated by Django 3.0 on 2019-12-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_launcher', '0008_remove_app_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='images',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin_launcher.Image'),
        ),
    ]
