# Generated by Django 3.0 on 2019-12-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_launcher', '0013_app_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='images',
        ),
        migrations.AddField(
            model_name='app',
            name='images2',
            field=models.ManyToManyField(default=None, to='admin_launcher.Image'),
        ),
    ]
