# Generated by Django 3.0 on 2019-12-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_launcher', '0014_auto_20191209_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='images2',
            new_name='images',
        ),
    ]
